# Generated by Django 3.2.8 on 2022-02-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='keywords',
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(to='website.ArticleTag'),
        ),
    ]
