# Generated by Django 3.2.8 on 2022-02-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enroll',
            options={'ordering': ['-course', '-user'], 'verbose_name_plural': 'Enrollment'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Description',
            new_name='description',
        ),
    ]
