# Generated by Django 3.2.9 on 2022-02-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_auto_20220220_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='allowed_in_course',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='enroll',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
