# Generated by Django 3.2.9 on 2022-02-21 10:06

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_alter_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', help_text='size of logo must be 100*100 and format must be png image file', keep_meta=True, null=True, quality=75, size=[600, 300], upload_to='instructor/images/courses/'),
        ),
    ]
